### PR TITLE
Feature/return localizedstring

### LINKED ISSUE #1: L.swift should generate a function which returns NSLocalizedString
Currently, we have to call NSLocalizedString function to access every localized string resource.

``` Swift
    label?.text = NSLocalizedString(L.foo.bar.message, comment: "")
```

But it will become much easier to access localizable.strings, if L.swift generate a function or a computed property returning localized string. Like this:

``` Swift
    label?.text = L.foo.bar.message.localizedString()

    // Is this much better?
    label?.text = L.foo.bar.message.localizedString
```

Thanks in advance :)

### PR DESCRIPTION
**Pull request by ykyouhei**
closed #1

### CODE REVIEW

**Comment by 3ign0n** [comment]
:+1: 
it looks great. thank you for your effort.

**Comment by uny** [comment]
:+1:

**Comment by Marimo67** [comment]
:+1: 
I'm Hanzo.

**Comment by ykyouhei** [comment]
@3ign0n @uny @Marimo67 Thanks!

**Pull request merged**
